language: node_js
node_js:
  - "6"
deploy:
  provider: heroku
  api_key:
    secure: nRuQJU8pbQvJIa44mZqu38rn0oH88ePEPJWUtO9zH6FJ38wIrVNi69KZm8b+y9I2wSZrzNe/g9j69kR53mdjg8L0idIhJiuL9NzAX3gTGaujcBUQlEIu1p45X5ayza2jbJHggIkywaci4dcQ6gDPYM/uBmDQoBOZYjGyf08zAUk/CII3cecxXaMJHFFQ0xNMNR+8ajl96BDIbGD+xFgJChjbMqjIZUDw9cO82oAtB18KkOUlh0wEpVXy7/3T2o41Qcz6qoa44nb1N9n/UgKFygBA1c2hY8oC6Gtyv4Um9jDrV57hX/aVqyI/wTaC1YqkG4XGsb0Zsyi10LC1o0BGJb6BbSeG1VwZSTDCtkyloJQXd94yE1fvMOfX4w4tNraZbuy499JlZ2aNwW+6+OqXRc48iPi8VpmQOPMpPwZpFbfLszPoGiMzf01EJAdCNT7mQud0j9Vd0by8AwXxcIcttPUSL+9a3AyowjWJAAre6k0U4szvcKUrb0lIZU5H87hURKkJcwcfBL8L50NeXRpKVMjPUv6+cg5l5bmYttr0JgEtyns7pCCpFr7V+11VJyKxWRkKusiux1AjPQ3SxBrKY0Azfd5zCQHyP54keRW5/+96eoNzVlOtZkUDuDC7xtLOdceNpgNJUjYPm69NvE5Xttkr4n0ixAtHjE8n9LHCAkM=
  app: tetrys
